---
title: "00_sampling"
author: "Timo Roettger"
date: "2023-05-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r loadData}

# nifty code using the pacman package
# it checks if the packages specified below are installed, if not, they will be installed, if yes, they will be loaded
if (!require("pacman")) install.packages("pacman")
pacman::p_load(rstudioapi, tidyverse)

# set the current working directory to the one where this file is
current_working_dir <- dirname(rstudioapi::getActiveDocumentContext()$path)
setwd(current_working_dir)

# let's load our dataset
data <- read_tsv("../parseHTML-MoBaPublications/prasedHTML_MoBaPublications.csv")
head(data)

```

## Distribution of publication year
Plotting the distribution of articles according to the year of publication:

```{r histogram}

ggplot(data,
       aes(x = Year)) + 
  geom_histogram(bins = 16,
                 binwidth = 1,
                 color = "darkgrey",
                 fill = "lightgrey"
                 ) +
  stat_bin(binwidth = 1, 
            geom = 'text', 
            color = 'black', 
            size = 3,
            aes(label = ..count..),
            position = position_stack(vjust = 1))

```

## Sampling
Draw a small subset of articles for manual inspection.

```{r sample}

set.seed(99)
sample(data$ApproximateTitle, 20, replace = FALSE)

# Sample through years
# Unique vector for each year
years <- unique(data$Year)

# Set the number of samples to be taken for each level
num_samples <- 30

# Set the number of samples to be taken for each level
year_sample <- data.frame(ApproximateTitle = as.character(),
                          Year = numeric(),
                          TexttoParse = as.character())

# Loop through the levels
for (i in years) {
  # Filter elements matching the current level
  year_i <- data[data$Year == i,]
  
  # Sample a subset for the current level
  year_subset <- year_i[sample(nrow(year_i), size = num_samples, replace = FALSE),]
  
  # Store in sample
  year_sample <- rbind(year_sample, year_subset)
  #title <- c(years,i)
}

# Q: How to deal with first 6 years having only scarce papers?
# A solution, sample exhaustively from 2006-2010, take 30 from rest (n = 76 + 12*30 = 436)
# A solution, sample exhaustively from 2006-2010, take 40 from rest (n = 76 + 12*40 = 556)

```
